export const KEY = {
  EMAIL: 'email',
  PASSWORD: 'password',
  SUBMIT: 'submit',
  SIGN_IN: 'sign-in',
  SIGN_UP: 'sign-up',
  FIRST_NAME: 'firstname',
  LAST_NAME: 'lastname',
  USERNAME: 'username',
  SSN: 'ssn',
  NAME: 'name',
  PHONE: 'phone',
  ADDRESS: 'address',
  STREET: 'street',
  CITY: 'city',
  STATE: 'state',
  POSTAL_CODE: 'postalCode',
  DATE_OF_BIRTH: 'dateOfBirth',
} as const
