export const KEY = {
  DEBIT: 'debit',
  CREDIT: 'credit',
  DESKTOP: 'desktop',
  MOBILE: 'mobile',
  EMAIL: 'email',
  PASSWORD: 'password',
  SUBMIT: 'submit',
  SIGN_IN: 'sign-in',
  SIGN_UP: 'sign-up',
  FIRST_NAME: 'firstName',
  LAST_NAME: 'lastName',
  USERNAME: 'username',
  SSN: 'ssn',
  NAME: 'name',
  PHONE: 'phone',
  ADDRESS: 'address1',
  STREET: 'street',
  CITY: 'city',
  STATE: 'state',
  POSTAL_CODE: 'postalCode',
  DATE_OF_BIRTH: 'dateOfBirth',
} as const
